export const GET_USER_LIST_REQUEST = "GET_USER_LIST_REQUEST";
export const GET_USER_LIST_RESPONSE = "GET_USER_LIST_RESPONSE";

// export const GET_USER_LAUNCH_LIST_RESPONSE = "GET_USER_LAUNCH_LIST_RESPONSE";
// export const GET_USER_LAND_LIST_RESPONSE = "GET_USER_LAND_LIST_RESPONSE";
// export const GET_USER_YEAR_LIST_RESPONSE = "GET_USER_YEAR_LIST_RESPONSE";